FLAG_IMAGES = {
    "argentina": "https://flagcdn.com/w320/ar.png",
    "brazil": "https://flagcdn.com/w320/br.png",
    "france": "https://flagcdn.com/w320/fr.png",
    "germany": "https://flagcdn.com/w320/de.png",
    "england": "https://flagcdn.com/w320/gb-eng.png",
    "portugal": "https://flagcdn.com/w320/pt.png",
    "netherlands": "https://flagcdn.com/w320/nl.png",
    "belgium": "https://flagcdn.com/w320/be.png",
    "croatia": "https://flagcdn.com/w320/hr.png",
    "morocco": "https://flagcdn.com/w320/ma.png",
    "japan": "https://flagcdn.com/w320/jp.png",
    "mexico": "https://flagcdn.com/w320/mx.png",
    "usa": "https://flagcdn.com/w320/us.png",
    "uruguay": "https://flagcdn.com/w320/uy.png",
    "colombia": "https://flagcdn.com/w320/co.png",
    "italy": "https://flagcdn.com/w320/it.png",
    "south korea": "https://flagcdn.com/w320/kr.png",
    "nigeria": "https://flagcdn.com/w320/ng.png",
    "cameroon": "https://flagcdn.com/w320/cm.png",
    "saudi arabia": "https://flagcdn.com/w320/sa.png",
    "australia": "https://flagcdn.com/w320/au.png",
    "canada": "https://flagcdn.com/w320/ca.png",
    "spain": "https://flagcdn.com/w320/es.png",
    "israel": "https://flagcdn.com/w320/il.png",
    "switzerland": "https://flagcdn.com/w320/ch.png",
    "sweden": "https://flagcdn.com/w320/se.png",
    "norway": "https://flagcdn.com/w320/no.png",
    "turkey": "https://flagcdn.com/w320/tr.png",
    "austria": "https://flagcdn.com/w320/at.png",
    "denmark": "https://flagcdn.com/w320/dk.png",
    "serbia": "https://flagcdn.com/w320/rs.png",
    "poland": "https://flagcdn.com/w320/pl.png",
    "senegal": "https://flagcdn.com/w320/sn.png",
    "ivory coast": "https://flagcdn.com/w320/ci.png",
    "ecuador": "https://flagcdn.com/w320/ec.png",
    "paraguay": "https://flagcdn.com/w320/py.png",
    "chile": "https://flagcdn.com/w320/cl.png",
}